/**
 * Alias en inglés → id estable. API-Football devuelve los nombres de selección
 * en inglés; este mapa permite resolverlos a nuestros ids del dominio.
 */
export const EN_TO_ID: Readonly<Record<string, string>> = {
  Mexico: 'mex',
  'South Korea': 'kor',
  'Korea Republic': 'kor',
  'Czech Republic': 'cze',
  Czechia: 'cze',
  'South Africa': 'rsa',
  Switzerland: 'sui',
  Canada: 'can',
  Qatar: 'qat',
  'Bosnia and Herzegovina': 'bih',
  Scotland: 'sco',
  Morocco: 'mar',
  Brazil: 'bra',
  Haiti: 'hai',
  USA: 'usa',
  'United States': 'usa',
  Australia: 'aus',
  Turkey: 'tur',
  Türkiye: 'tur',
  Paraguay: 'par',
  Germany: 'ger',
  'Ivory Coast': 'civ',
  "Côte d'Ivoire": 'civ',
  Ecuador: 'ecu',
  'Curacao': 'cuw',
  Curaçao: 'cuw',
  Sweden: 'swe',
  Japan: 'jpn',
  Netherlands: 'ned',
  Tunisia: 'tun',
  Belgium: 'bel',
  Egypt: 'egy',
  Iran: 'irn',
  'IR Iran': 'irn',
  'New Zealand': 'nzl',
  Spain: 'esp',
  Uruguay: 'uru',
  'Cape Verde': 'cpv',
  'Cabo Verde': 'cpv',
  'Saudi Arabia': 'ksa',
  France: 'fra',
  Norway: 'nor',
  Senegal: 'sen',
  Iraq: 'irq',
  Austria: 'aut',
  Argentina: 'arg',
  Algeria: 'alg',
  Jordan: 'jor',
  Portugal: 'por',
  Colombia: 'col',
  'DR Congo': 'cod',
  'Congo DR': 'cod',
  Uzbekistan: 'uzb',
  Croatia: 'cro',
  England: 'eng',
  Ghana: 'gha',
  Panama: 'pan',
};
